
/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],
    plugins: [require("daisyui")],
    daisyui: {
        themes: [
            {
                light: {
                    "primary": "#2b49ff",
                    "secondary": "#00b5b4",
                    "accent": "#ff301c",
                    "neutral": "#0f1023",
                    "base-100": "#fff",
                    "base-200": "#f6f7fb",
                    "base-300": "#fafbfc",
                    "info": "#98d7f0",
                    "success": "#9cdcc5",
                    "warning": "#e0ca96",
                    "error": "#f8bbb0",
                },
            },
            {
                dark: {
                    "primary": "#2b49ff",
                    "secondary": "#00b5b4",
                    "accent": "#ff301c",
                    "neutral": "#4e5168",
                    "base-100": "#393b51",
                    "base-200": "#2b2d43",
                    "base-300": "#0f1023",
                    "info": "#98d7f0",
                    "success": "#9cdcc5",
                    "warning": "#e0ca96",
                    "error": "#f8bbb0",
                },
            },
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
            "dim",
            "nord",
            "sunset",
        ],
    },
};
